### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by wozniakm** [pleerock/serializer.ts#1]
Hello, I see your package really useful for me, but I have troubles with typings. Could you please instruct me how to install typings for your package? Running "typings install" does not change anything.

Thanks, Matt

**Comment by pleerock** [comment]
Hello,
may I confirm something: do you use angular.beta6 project with typings or you are doing something else?
at the moment because of this [issue](https://github.com/typings/typings/issues/108) you cannot add serializer as a dependency into your typings.json, so you need manually add to your typings.json all ambient dependencies from serializer.ts (this is only es6-shim, and if you are using angular - it means you already have es6-shim in your ambient dependencies and you dont need to do anything)
Did you try to start using library despite the fact that typings install does not install anything new for you?

**Comment by wozniakm** [comment]
Yes, I'm using the same Angular 2.0.0-beta.6 with typings. I also have es6-shim in my ambient dependencies. The problem is that when I try to import serializer.ts to any file in my project, typescript is throwing an error that serializer.ts can not be found, but serializer.ts directory is present in node modules directory. Any ideas?

**Comment by pleerock** [comment]
can you provide a code snippet how do you import it? Also do you use "moduleResolution": "node" in your tsconfig?

**Comment by wozniakm** [comment]
I was trying to import it as you suggested in readme, but it was throwing an error that can not resolve file. Below is the snippet:

`import {serialize} from "serializer.ts";`

It started to work when I changed that into:

`import {serialize} from 'serializer.ts/serializer';`

It's now showing warnings that can not find source files and indeed they are not present in module directory.

**Comment by pleerock** [comment]
thats strange, I just created a test project and installed it from scratch - everything looks working. If you can attach or send me your test project I'll take a look on that

**Comment by wozniakm** [comment]
I am using [https://github.com/angularclass/angular2-webpack-starter](url) as a base and would really appreciate if you can take a look on this.

**Comment by pleerock** [comment]
sorry that was an error in docs. in readme only "example with angular" had correct example. you should use `import {serialize} from "serializer.ts/Serializer";`

> import {serialize} from 'serializer.ts/serializer';
> It's now showing warnings that can not find source files and indeed they are not present in module directory.

maybe its because you are imported `serializer.ts/serializer` instead of `serializer.ts/Serializer` ?

**Comment by wozniakm** [comment]
It is working fine now, the warnings disappeared spontaneously. For someone who is starting with TypeScript, like me, that might by serious problem. Thanks for help :)

**Comment by pleerock** [comment]
yw)
